dependencies:
- name: bdd-golang-http-1549315068
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: jx
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.22
- name: mwm-golang-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.21
- name: steve-golang
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.34
